openapi: 3.0.0
info:
  title: Car Management API
  version: 1.0.0
paths:
  /users/{user_id}/cars:
    get:
      summary: Get all cars associated with a user
      parameters:
        - in: path
          name: user_id
          required: true
          schema:
            type: string
          description: User ID
      responses:
        "200":
          description: A list of cars
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    car_id:
                      type: integer
                      example: 1
                    car_name:
                      type: string
                      example: "Toyota Prius"
                    carmodelnum:
                      type: string
                      example: "X123"
                    car_color:
                      type: string
                      example: "Blue"
                    car_mileage:
                      type: integer
                      example: 10000
                    car_isflooding:
                      type: boolean
                      example: false
                    car_issmoked:
                      type: boolean
                      example: false
                    car_image_url:
                      type: string
                      format: uri
                      example: "https://cdn.autoc-one.jp/images/article/202103/18020439026_fbc4_o.jpg"
                    created_at:
                      type: string
                      format: date-time
                      example: "2023-06-21T10:20:30Z"
                    updated_at:
                      type: string
                      format: date-time
                      example: "2023-06-21T10:20:30Z"
                    FuelEfficiency:
                      type: array
                      items:
                        type: object
                        properties:
                          fe_id:
                            type: integer
                            example: 1
                          car_id:
                            type: integer
                            example: 1
                          fe_date:
                            type: string
                            format: date-time
                            example: "2023-07-01T10:20:30Z"
                          fe_amount:
                            type: number
                            example: 10
                          fe_unitprice:
                            type: number
                            example: 150
                          fe_mileage:
                            type: number
                            example: 100
                          created_at:
                            type: string
                            format: date-time
                            example: "2023-07-01T10:20:30Z"
                          updated_at:
                            type: string
                            format: date-time
                            example: "2023-07-01T10:20:30Z"
                    odd_after_wash:
                      type: number
                      example: 500
                    odd_after_exchange:
                      type: number
                      example: 300
              example:
                - car_id: 1
                  car_name: "Toyota Prius"
                  carmodelnum: "X123"
                  car_color: "Blue"
                  car_mileage: 10000
                  car_isflooding: false
                  car_issmoked: false
                  car_image_url: "https://cdn.autoc-one.jp/images/article/202103/18020439026_fbc4_o.jpg"
                  created_at: "2023-06-21T10:20:30Z"
                  updated_at: "2023-06-21T10:20:30Z"
                  FuelEfficiency: []
                  odd_after_wash: 500
                  odd_after_exchange: 300
                - car_id: 2
                  car_name: "Honda Accord"
                  carmodelnum: "Y456"
                  car_color: "Red"
                  car_mileage: 20000
                  car_isflooding: false
                  car_issmoked: false
                  car_image_url: "https://www.toyota-body.co.jp/images/auto/minivan.jpg"
                  created_at: "2023-06-21T10:20:30Z"
                  updated_at: "2023-06-21T10:20:30Z"
                  FuelEfficiency: []
                  odd_after_wash: 500
                  odd_after_exchange: 300
